version: '3'
services:
  db:
    container_name: mongo
    image: mongo:latest
    ports:
      - 27018:27018

  backend:
    image: backend
    container_name: backend
    ports:
      - 4205:4205
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /usr/app/node_modules/.bin/nodemon -L index.js
    depends_on:
      - db
    volumes:
      - ./backend:/usr/app

  frontend:
    image: frontend
    container_name: frontend
    ports:
      - 80:80
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/app
